### ISSUE TITLE
如何通过API进行集合offer报价和履行集合offer

### ISSUE THREAD

**Issue by jqkafans** [cryptochou/seaport-analysis#1]
大佬写的非常好，受益匪浅。
但我在实践过程中，criteriaResolvers的criteriaProof这个参数怎么获取呢？
盼复，先感谢大佬为敬。

**Comment by ByteWizardJ** [comment]
这里用到了一个第三方库：MerkleTree.js。

具体使用可以参考seaport官方给的测试用例：[https://github.com/ProjectOpenSea/seaport-js/blob/main/src/__tests__/criteria-based.spec.ts](https://github.com/ProjectOpenSea/seaport-js/blob/main/src/__tests__/criteria-based.spec.ts)

可以参考一下上面这个文件的383行左右的代码。

**Comment by jqkafans** [comment]
感谢大大解答
