### ISSUE TITLE
ahha

### ISSUE THREAD

**Issue by CostofLivingFree** [cryptochou/seaport-analysis#2]
no issue solved

**Comment by ByteWizardJ** [comment]
Sorry, but I can't get more information from your code. Maybe you can get more information from the test cases in the seaport code repository. Such as https://github.com/ProjectOpenSea/seaport/blob/main/test/basic.spec.ts

**Comment by CostofLivingFree** [comment]
I was tripping my code is right

**Comment by ByteWizardJ** [comment]
I think there is a problem with your order data, the original meaning of the Match Orders type of order is to match two or more orders that already exist. And the offer and consideration items of these orders match each other exactly.

The `fulfillments` are specific information about which item in each order offer matches which consideration item in another order. I see that your fulfillments data has both `offerComponents` and `considerationComponents` for the same order.

<img width="329" alt="截屏2022-11-19 17 34 11" src="https://user-images.githubusercontent.com/7424938/202844557-82d4f79c-677b-4cd1-8262-866073e50db6.png">

Here's an example of fulfillments from my article。You can check it out。

```json
[{ // 第 1 个订单的 offer 中第 1 个项目与第 2 个订单的 consideration 的第 1 个项目匹配
  "offerComponents": [{
    "orderIndex": 0,
    "itemIndex": 0
  }],
  "considerationComponents": [{
    "orderIndex": 1,
    "itemIndex": 0
  }]
}, 
{ // 第 1 个订单的 offer 中第 2 个项目与第 2 个订单的 consideration 的第 2 个项目匹配
  "offerComponents": [{
    "orderIndex": 0,
    "itemIndex": 1
  }],
  "considerationComponents": [{
    "orderIndex": 1,
    "itemIndex": 1
  }]
}, 
{ // 第 2 个订单的 offer 中第 1 个项目与第 1 个订单的 consideration 的第 1 个项目匹配
  "offerComponents": [{
    "orderIndex": 1,
    "itemIndex": 0
  }],
  "considerationComponents": [{
    "orderIndex": 0,
    "itemIndex": 0
  }]
}, 
{ // 第 2 个订单的 offer 中第 1 个项目与第 1 个订单的 consideration 的第 2 个项目匹配
  "offerComponents": [{
    "orderIndex": 1,
    "itemIndex": 0
  }],
  "considerationComponents": [{
    "orderIndex": 0,
    "itemIndex": 1
  }]
}, 
{ // 第 2 个订单的 offer 中第 1 个项目与第 1 个订单的 consideration 的第 3 个项目匹配
  "offerComponents": [{
    "orderIndex": 1,
    "itemIndex": 0
  }],
  "considerationComponents": [{
    "orderIndex": 0,
    "itemIndex": 2
  }]
}]
```

**Comment by CostofLivingFree** [comment]
I thought you were pro cryptochou but you are amateur

**Comment by CostofLivingFree** [comment]
In the event that I am executing a private sale, as shown in my original code - is my logic with regard to the matchOrder incorrect? If so, do you mind assisting me in what I need to do different to match the order that I am trying to execute in the original example.

**Comment by CostofLivingFree** [comment]
> In the event that I am executing a private sale, as shown in my original code - is my logic with regard to the matchOrder incorrect? If so, do you mind assisting me in what I need to do different to match the order that I am trying to execute in the original example.

I understand my fulfillments are definitely incorrect, however, are you saying the rest of the code logic is incorrect as well?

**Comment by CostofLivingFree** [comment]
if you are interested https://github.com/cheungchingli/seaport-js-gas/commit/e79a4f97ffaf88d5118ce7fc342bf13635b17ef2#diff-2c635709d0b406f66be68853b3022378855bdab68f21afddfd627d09b78032ee here is a link to a privatelisting matchorders where the implementation is the same
